field.storage_settings.entity_reference_hierarchy:
  type: field.storage_settings.entity_reference
  label: 'Entity reference hierarchy field storage settings'

field.field_settings.entity_reference_hierarchy:
  type: field.field_settings.entity_reference
  label: 'Entity reference hierarchy field settings'
  mapping:
    weight_min:
      type: integer
      label: 'Min weight'
    weight_max:
      type: integer
      label: 'Max weight'
    weight_label:
      type: label
      label: 'Weight label'
