# Schema for the views plugins of the module.
views.argument.entity_hierarchy_argument_is_child_of_entity:
  type: views_argument
  label: 'Child entities'
  mapping:
    depth:
      type: integer
      label: 'Depth'

views.argument.entity_hierarchy_argument_is_child_of_entity_revision:
  type: views.argument.entity_hierarchy_argument_is_child_of_entity
